# Generated by Django 3.2.25 on 2024-10-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Delivery_man', 'Delivery_man'), ('Store_admin', 'Store_admin')], default='Customer', max_length=150),
        ),
    ]
