# Generated by Django 3.2.25 on 2024-10-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_status',
        ),
    ]
