# Generated by Django 3.2.25 on 2024-10-15 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0004_remove_ordereditems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
