# Generated by Django 3.2.25 on 2024-10-14 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_name'),
        ('accounts', '0002_auto_20241010_0705'),
        ('orders', '0005_auto_20241010_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_signature',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.TextField(default=datetime.datetime(2024, 10, 14, 10, 36, 5, 855527, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_boy', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.store'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
