# Generated by Django 3.2.25 on 2024-10-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
