# Generated by Django 3.2.25 on 2024-10-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='no_of_pices',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serves',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
