# Generated by Django 3.2.25 on 2024-10-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='products.store')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceArea',
        ),
    ]
