# Generated by Django 3.2.25 on 2024-10-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20241017_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_pices',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serves',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
