# Generated by Django 3.2.25 on 2024-10-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_store_store_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='pincode',
        ),
    ]
