# Generated by Django 3.2.25 on 2024-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
