# Generated by Django 3.2.25 on 2024-10-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0004_remove_store_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
