# Generated by Django 3.2.25 on 2024-10-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_store_store_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
